---
swagger: "2.0"
info:
  title: Watch Wizard
  description: API for Watch Wizard application
  version: 1.0.0
basePath: "/"
paths:
  "/trakt/auth-code":
    get:
      summary: Trakt GetAuthCode Function
      description: Gets a device code to be used for authenticating with the Trakt API
      operationId: TraktGetAuthCodeFunction
      produces:
        - application/json
      responses:
        200:
          description: Success
        404:
          description: Not found
        500:
          description: 500 Internal Server Error
        503:
          description: SERVICE UNAVAILABLE
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TraktGetAuthCodeFunction.Arn}/invocations"
  "/trakt/authenticate-device":
    post:
      summary: Trakt Authenticate Function
      description: Authenticates a device for use with the Trakt API
      operationId: TraktAuthenticateFunction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: device_auth_data
          description: The DeviceAuthData to use for authentication with the Trakt API
          schema:
            $ref: "#/definitions/DeviceAuthData"
      responses:
        200:
          description: Success
        404:
          description: Not found
        409:
          description: You already approved this code
        410:
          description: The tokens have expired, restart the process
        418:
          description: You explicitly denied this code
        500:
          description: 500 Internal Server Error
        503:
          description: SERVICE UNAVAILABLE
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TraktAuthenticateDeviceFunction.Arn}/invocations"
  "/trakt/recommend-movie":
    get:
      summary: Trakt RecommendMovie Function
      description: Recommends a movie using Trakt API
      operationId: TraktRecommendMovieFunction
      produces:
        - application/json
      responses:
        200:
          description: Success
        404:
          description: Not found
        500:
          description: 500 Internal Server Error
        503:
          description: SERVICE UNAVAILABLE
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TraktRecommendMovieFunction.Arn}/invocations"
  "/trakt/recommend-movie-and-speak":
    post:
      summary: Trakt RecommendMovie Function
      description: Recommends a movie using Trakt API
      operationId: TraktRecommendMovieFunction
      produces:
        - application/json
      responses:
        200:
          description: Success
        404:
          description: Not found
        500:
          description: 500 Internal Server Error
        503:
          description: SERVICE UNAVAILABLE
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TraktRecommendMovieAndSpeakFunction.Arn}/invocations"
definitions:
  DeviceAuthData:
    type: object
    required:
      - device_code
      - poll_interval
    properties:
      device_code:
        type: string
      poll_interval:
        type: integer
      user_code:
        type: string
      verification_url:
        type: string
