AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for WatchWizard Application
Globals:
  Function:
    Runtime: python3.9
    Timeout: 60
    Environment:
      Variables:
        ServiceName: !Ref ServiceName
        ServiceSecretName: !Sub "apps/${ServiceName}"
        TraktSecretName: !Sub "apps/${ServiceName}-Trakt"
        SecretsManagerEndpoint: ""
Parameters:
  ServiceName:
    Type: String
    Default: WatchWizard
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: !Sub "${ServiceName}-Lambda-Policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:PutSecretValue"
                Resource:
                  - !Ref SecretsManagerSecret
                  - !Ref SecretsManagerTraktSecret
            
  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "apps/${ServiceName}"
      Description: !Sub "Secret values for the ${ServiceName} application"
  
  SecretsManagerTraktSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "apps/${ServiceName}-Trakt"
      Description: !Sub "Trakt-specific secret values for the ${ServiceName} application"

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: !Sub "${ServiceName}-ApiGateway"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: "./api.yaml"
      MethodSettings:
      - LoggingLevel: ERROR
        ResourcePath: "/*"
        HttpMethod: "*"

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "${ServiceName}-Default-Usage-Plan"
      ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: !Ref ApiGatewayApi.Stage
      Description: !Sub "Default usage plan for the ${ServiceName} service"
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 200
        RateLimit: 100

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "${ServiceName}-Default-API-Key"
      Description: !Sub "Default API key for the ${ServiceName} service"
      Enabled: True
      StageKeys:
        - RestApiId: !Ref ApiGatewayApi
          StageName: !Ref ApiGatewayApi.Stage

  UsagePlanApiKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties: 
      KeyId: !Ref ApiKey
      KeyType: 'API_KEY'
      UsagePlanId: !Ref UsagePlan

  ConfigGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-Config-Get"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watch_wizard/
      Handler: handlers/api/config.get_config

  TraktGetAuthCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-Trakt-GetAuthCode"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watch_wizard/
      Handler: handlers/api/trakt.get_auth_code
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/trakt/auth-code"
            Method: get
            Auth:
              ApiKeyRequired: true

  TraktAuthenticateDeviceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-Trakt-AuthenticateDevice"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watch_wizard/
      Handler: handlers/api/trakt.authenticate_device
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/trakt/authenticate-device"
            Method: post
            Auth:
              ApiKeyRequired: true

  PlexHealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-Plex-HealthCheck"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watch_wizard/
      Handler: handlers/api/plex.health_check
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/plex/health"
            Method: get
            Auth:
              ApiKeyRequired: true

  SearchMediaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-SearchMedia"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watch_wizard/
      Handler: handlers/api/media.search
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/media/search"
            Method: get
            Auth:
              ApiKeyRequired: true

  RecommendMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-RecommendMovie"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watch_wizard/
      Handler: handlers/api/media.recommend_movie
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/media/recommend-movie"
            Method: get
            Auth:
              ApiKeyRequired: true

  AlexaSkillsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-AlexaSkillsApi"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watch_wizard/
      Handler: handlers/api/alexa.handle_skill_request
      Events:
        Post:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/alexa/skills"
            Method: post
            Auth:
              ApiKeyRequired: false

  AlexaSkillsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-AlexaSkills"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watch_wizard/
      Handler: handlers/alexa/lambdas.handle_skill_request
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
