AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for WatchWizard Application
Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    Environment:
      Variables:
        ServiceName: !Ref ServiceName
Parameters:
  ServiceName:
    Type: String
    Default: WatchWizard
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ServiceName}-Lambda-Policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:PutSecretValue"
                Resource:
                  - !Ref SecretsManagerTraktSecret
            
  SecretsManagerTraktSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "apps/${ServiceName}-Trakt"
      Description: !Sub "Trakt-specific secret values for the ${ServiceName} application"
      SecretString: '{"CLIENT_ID": "", "CLIENT_SECRET": ""}'

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "Prod"
      Name: !Sub "${ServiceName}-ApiGateway"
      Auth:
        ApiKeyRequired: true
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: "./api.yaml"
      MethodSettings:
      - LoggingLevel: ERROR
        ResourcePath: "/*"
        HttpMethod: "*"

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "${ServiceName}-Default-Usage-Plan"
      ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: Prod
      Description: !Sub "Default usage plan for the ${ServiceName} service"
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 200
        RateLimit: 100

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "${ServiceName}-Default-API-Key"
      Description: !Sub "Default API key for the ${ServiceName} service"
      Enabled: True
      StageKeys:
        - RestApiId: !Ref ApiGatewayApi
          StageName: Prod

  UsagePlanApiKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties: 
      KeyId: !Ref ApiKey
      KeyType: 'API_KEY'
      UsagePlanId: !Ref UsagePlan

  TraktGetAuthCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-Trakt-GetAuthCode"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watch_wizard/
      Handler: handlers/trakt_handler.get_auth_code
      Environment:
        Variables:
          TraktSecretName: !Sub "apps/${ServiceName}-Trakt"
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/trakt/auth-code"
            Method: get

  TraktAuthenticateDeviceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-Trakt-AuthenticateDevice"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watch_wizard/
      Handler: handlers/trakt_handler.authenticate_device
      Environment:
        Variables:
          TraktSecretName: !Sub "apps/${ServiceName}-Trakt"
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/trakt/authenticate-device"
            Method: post