name: Deploy Pipeline to CloudFormation

on: 
  workflow_dispatch:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  deploy:
    name: Deploy pipeline to AWS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ca-central-1
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}

      - name: Deploy to AWS CloudFormation
        id: deploy-pipeline
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: WatchWizardPipeline
          template: pipeline.yaml
          parameter-overrides: "RepositoryBranchName=${{ github.ref_name }},ArtifactsBucketName=${{ secrets.AWS_ARTIFACTS_BUCKET_NAME }},RepositoryConnectionArn=${{ secrets.AWS_REPOSITORY_CONNECTION_ARN }}"
          no-fail-on-empty-changeset: "1"